on:
  push:
    branches:
      - release

jobs:
  version_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update version in csproj
        run: |
          # Get the current version from the csproj file
          CURRENT_VERSION=$(grep -oP '<Version>\K[^<]+' YourProject.csproj)
          
          # Increment the version (you can use any logic you want here)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F '.' '{$NF = $NF + 1;} 1' OFS='.')

          # Update the csproj file with the new version
          sed -i "s|<Version>$CURRENT_VERSION</Version>|<Version>$NEW_VERSION</Version>|" YourProject.csproj

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json